configured_endpoints: 78
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/testspotify%2Fspotted-6ed0d4b1dcf6a6bda1f397c9e7dafbef6c280e5fa6586c9e37025f2fc3e9838c.yml
openapi_spec_hash: e96ace8fb2e27de2e776bd575bcf93a1
config_hash: fdc572b7cc092a088d154e937ce5eb60
