configured_endpoints: 89
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/testspotify%2Fspotted-bf0fbeb413f03d99b1fbda72178d6ef3eb4cd275144b62d250dad89490f2cdcd.yml
openapi_spec_hash: e96ace8fb2e27de2e776bd575bcf93a1
config_hash: 800a78ddfc666f6fddddef874207b533
