#!/usr/bin/env bash

set -euo pipefail

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/cjavdev/spotted-go,github.com/stainless-sdks/spotted-go"

go build -o terraform-provider-spotted
