#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/cjavdev/spotted-go,github.com/stainless-sdks/spotted-go"

REPLACEMENT="${1:-"../spotted-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/cjavdev/spotted-go="$REPLACEMENT"
go mod tidy -e
