#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/cjavdev/spotted-go,github.com/stainless-sdks/spotted-go"

echo "==> Running Go build"
go build ./...

echo "==> Checking tests compile"
go test -run=^$ ./...
